# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Test-agents

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: FortifySCA@7
  inputs:
    applicationType: 'other'
    fortifySourceTranslate: '**/*.tf'
    fortifyBuildId: 'ejemplo-terraform'
    fortifyScanType: 'LocalScan'

- powershell: |
    fcli ssc session login --url https://win-rv0b57m816h:8443/ssc --user Admin --password Avattar.2026 --sc-sast-url https://win-rv0b57m816h:8444/scancentral-ctrl -c ClientSSC --disable sc-dast
  
    fcli ssc artifact upload --av terraform:1 -f $(Build.ArtifactStagingDirectory)\sca_artifacts\ejemplo-terraform.fpr
  displayName: 'PowerShell multilinea'
