# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: DemoRun

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: FortifySCA@7
  inputs:
    applicationType: 'other'
    fortifySourceTranslate: '**/*.tf'
    fortifyBuildId: 'ejemplo-terraform'
    fortifyScanType: 'LocalScan'

- powershell: |
    fcli ssc session login --url https://win-9d5thk26lqu:8443/ssc --user jhernandez --password Avattar.2025 --sc-sast-url https://win-9d5thk26lqu:8444/scancentral-ctrl/ -c ClientSSC --disable sc-dast
  
    fcli ssc artifact upload -av terraform:1.0 -f $(Build.ArtifactStagingDirectory)\sca_artifacts\ejemplo-terraform.fpr
  displayName: 'PowerShell multilinea'
